### ISSUE TITLE
♻️ Refactor FeatureCarousel Component - Different screen sizes

### ISSUE THREAD

**Issue by joshbermanssw** [SSWConsulting/SSW.Products#14]
As per my conversation with @isaaclombardssw in #12 we want to refactor how the FeatureCarousel component renders content on different screen sizes. 

Instead of using the useEffect hook to check for the window size and then track this via a useState, we want to create 2 different components and then in the primary `FeatureHorizontalCarousel` component render each of these using tailwinds hidden / block properties on either sm: md: lg: xl: screens 

**Tasks**
- [ ] Extrapolate the two views (small/medium, large+) into different components 
- [ ] Render the two views in the `FeatureHorizontalCarousel` component using the tailwind hidden properties and screen sizes
- [ ] Cleanup unnecessary hooks
