### ISSUE TITLE
📝 YakShaver Website - Use 🐂 (ox) Emoji after YakShaver mentions

### ISSUE THREAD

**Issue by edkranz** [SSWConsulting/SSW.Products#52]
Hi Team!

### Pain

YakShaver should be associated with the 🐂 (ox) emoji, and it is not mentioned anywhere on the www.yakshaver.ai website.

### Tasks
- [ ] Add the 🐂 (ox) emoji after mentions of YakShaver on the website, as per the screenshots.

### Acceptance Criteria
- [ ] The 🐂 emoji is found on the _About Us_ page as per the screenshot.
- [ ] The 🐂 emoji is found on the _Blogs_ page as per the screenshot.
- [ ] The 🐂 emoji is found on the _Docs_ page as per the screenshot.
- [ ] The 🐂 emoji is found in the footer as per the screenshot.
- [ ] The 🐂 emoji is found on the Home page as per the screenshot.
- [ ] The 🐂 emoji is found on the "talk to an expert" component as per the screenshot.

### Screenshots
![Image](https://github.com/user-attachments/assets/4b39abfa-8795-4d7f-863a-7f71f0f66495)
**Figure: Proposed inclusion of 🐂 on the "About Us" page.**

---

![Image](https://github.com/user-attachments/assets/432a5918-9e48-4224-a048-2e72053e8c71)
**Figure: Proposed inclusion of 🐂 on the "Blogs" page.**

---

![Image](https://github.com/user-attachments/assets/1a0d7505-f5ee-4107-a859-00e9d0731ed7)
**Figure: Proposed inclusion of 🐂 on the "Docs" page.**

---

![Image](https://github.com/user-attachments/assets/1fe01b43-2e2e-408f-99e5-feb50ee1fadc)
**Figure: Proposed inclusion of 🐂 on the footer.**

---

![Image](https://github.com/user-attachments/assets/f58bb569-9f46-4dc7-ab19-a4c0ef64f4ee)
**Figure: Proposed inclusion of 🐂 on the "Home" page.**

---

![Image](https://github.com/user-attachments/assets/0ff1ebc2-490c-41d4-96f0-3100d0c00195)
**Figure: Proposed inclusion of 🐂 on the "talk to an expert" component.**

**Comment by Calinator444** [comment]
I can't tell if this is an april fools joke 😆

**Comment by edkranz** [comment]
@Calinator444 It was a suggestion by Adam
